- name: Gather Facts
  gather_facts: true
  hosts: local

- name: Setup dotfiles
  gather_facts: no
  hosts: local
  user: '{{ ansible_user_id }}'
  become: true
  become_user: root
  become_method: sudo
  roles:
    - role: base
      tags:
        - base
        - wsl
    - role: git
      tags:
        - git
        - wsl
    - role: interface
      tags:
        - interface
    - role: fonts
      tags:
        - fonts
    - role: zsh
      tags:
        - zsh
        - wsl
    - role: fzf
      tags:
        - fzf
        - wsl
    - role: ag
      tags:
        - ag
        - wsl
    - role: gron
      tags:
        - gron
        - wsl
    - role: resty
      tags:
        - resty
        - wsl
    - role: nvm
      tags:
        - nvm
        - wsl
    - role: pyenv
      tags:
        - pyenv
        - wsl
    - role: rbenv
      tags:
        - rbenv
        - wsl
    - role: tmux
      tags:
        - tmux
        - wsl
    - role: termite
      tags:
        - termite
    - role: vscode
      tags:
        - vscode
    - role: vim
      tags:
        - vim
        - wsl
    - role: docker
      tags:
        - docker
        - wsl
    - role: elasticsearch
      tags:
        - elasticsearch
        - wsl
    - role: redis
      tags:
        - redis
        - wsl
    - role: psql
      tags:
        - psql
        - wsl
    - role: vagrant
      tags:
        - vagrant
        - wsl
    - role: azurecli
      tags:
        - azurecli
        - wsl
    - role: azuredatastudio
      tags:
        - azuredatastudio
    - role: spotify
      tags:
        - spotify
    - role: vlc
      tags:
        - vlc
    - role: heroku
      tags:
        - heroku
    - role: gimp
      tags:
       - gimp
    - role: libreoffice
      tags:
       - libreoffice
    - role: wallpapers
      tags:
        - wallpapers
    - role: numix
      tags:
        - numix
    - role: adapta
      tags:
        - adapta
    - role: chrome
      tags:
        - chrome
    - role: flameshot
      tags:
        - flameshot
    - role: peek
      tags:
        - peek
    - role: discord
      tags:
        - discord
    - role: telegram
      tags:
        - telegram
    - role: slack
      tags:
        - slack
    - role: finish
      tags:
        - finish
        - wsl
