
- block:
  - name: Install Gnome dependencies
    apt:
      name: '{{ item }}'
      state: latest
    loop:
      - gnome-shell-extensions
      - dconf-editor
      - gnome-tweak-tool
      - gnome-common
      - pkg-config
      - autoconf
      - automake
      - gettext
    tags:
      - deps
      - deps-interface

  - block:
    - name: Configure enabled extensions
      gsettings:
        key: org.gnome.shell.enabled-extensions
        value: "{{ lookup('file', 'enabled-extensions.txt') }}"
        state: present
        user: '{{ ansible_user_id }}'

    - name: Move button layout to left
      gsettings:
        key: org.gnome.desktop.wm.preferences.button-layout
        value: "'close,minimize,maximize:'"
        state: present
        user: '{{ ansible_user_id }}'

    - name: Configure favorite apps
      gsettings:
        key: org.gnome.shell.favorite-apps
        value: "{{ lookup('file', 'favorite-apps.txt') }}"
        state: present
        user: '{{ ansible_user_id }}'

    - name: Resize Dash icons to 30
      gsettings:
        key: org.gnome.shell.extensions.dash-to-dock.dash-max-icon-size
        value: 30
        state: present
        user: '{{ ansible_user_id }}'

    - name: Remove Trash and Volumes from Desktop
      gsettings:
        key: '{{ item }}'
        value: 'false'
        state: present
        user: '{{ ansible_user_id }}'
      loop:
        - org.gnome.nautilus.desktop.trash-icon-visible
        - org.gnome.nautilus.desktop.volumes-visible

    - name: Show date on top panel
      gsettings:
        key: org.gnome.desktop.interface.clock-show-date
        value: 'true'
        state: present
        user: '{{ ansible_user_id }}'

    tags:
      - gsettings
      - gsettings-interface


  - import_tasks: panel-osd.yml

  - import_tasks: terminal.yml

  tags:
    - install
    - install-interface
