- block:
  - name: Check tmux version
    command: tmux -V
    register: tmux_installed
    ignore_errors: true
    tags:
      - check
      - check-tmux

  - import_tasks: install.yml
    when: >
      tmux_installed.rc != 0 or
      tmux_version not in tmux_installed.stdout

  - name: Check if plugins folder exists
    command: 'ls {{ ansible_env.HOME}}/.tmux/plugins'
    register: plugins_folder_exists
    ignore_errors: true

  - name: Create plugins folder
    file:
      path: '{{ ansible_env.HOME}}/.tmux/plugins'
      state: directory
      owner: '{{ ansible_user_id }}'

  - name: Copy .tmux.conf
    copy:
      src: .tmux.conf
      dest: '{{ ansible_env.HOME }}/.tmux.conf'
      owner: '{{ ansible_user_id }}'

  - import_tasks: tpm.yml
    tags:
      - install-tpm

  - import_tasks: tmuxinator.yml
    tags:
      - install-tmuxinator

  - name: Restart tmux
    command: tmux kill-server
    ignore_errors: true

  tags:
    - install
    - install-tmux
