
- block:
  - name: Check if docker is installed
    command: docker -v
    register: docker_installed
    ignore_errors: true
    tags:
      - check
      - check-docker

  - import_tasks: install.yml
    when: docker_installed.rc != 0

  - name: Add docker group
    shell: groupadd docker
    ignore_errors: true

  - name: Add user to docker group
    shell: usermod -aG docker {{ ansible_user_id }}

  - name: Check docker-compose version
    command: docker-compose --version
    register: docker_compose_current_version
    ignore_errors: true

  - name: Get current OS name and version
    shell: uname -s -m | awk '{v=$1"-"$2; print v}'
    register: os_name_version

  - name: Install docker-compose
    get_url:
      url: 'https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ os_name_version.stdout }}'
      dest: /usr/local/bin/docker-compose
      mode: 0755
    # when: >
    #   docker_compose_current_version.stdout is defined
    #   and docker_compose_version not in docker_compose_current_version.stdout
    #   or docker_compose_current_version.stdout is not defined

  tags:
    - install
    - install-docker
