
- block:
  - name: Check if docker is installed
    command: docker -v
    register: docker_installed
    ignore_errors: yes
    tags:
      - check
      - check-docker

  - import_tasks: install.yml
    when: docker_installed.rc != 0

  - name: Add docker group
    shell: groupadd docker
    ignore_errors: true

  - name: Add user to docker group
    shell: usermod -aG docker {{ ansible_user_id }}

  - name: Check if docker-compose is installed
    command: docker-compose --version
    register: docker_compose_installed
    ignore_errors: true

  - name: Get current OS name and version
    shell: uname -s -m | awk '{v=$1"-"$2; print v}'
    register: os_name_version

  - name: Install docker-compose
    get_url:
      url: 'https://github.com/docker/compose/releases/download/1.25.0/docker-compose-{{ os_name_version.stdout }}'
      dest: /usr/local/bin/docker-compose
      mode: 0755
    when: docker_compose_installed.rc != 0

  tags:
    - install
    - install-docker
