- block:
  - name: Install latest Vim
    apt:
      name: vim
      state: latest

  - name: Make sure Vim plugins folder exists
    file:
      path: '{{ ansible_env.HOME }}/.vim/autoload'
      state: directory
      owner: '{{ ansible_user_id }}'

  - name: Install vim-plug
    get_url:
      url: '{{ vim_plug_url }}'
      dest: '{{ ansible_env.HOME }}/.vim/autoload/plug.vim'
      owner: '{{ ansible_user_id }}'

  - name: Clone sample vimrc repository
    git:
      repo: https://github.com/amix/vimrc.git
      dest: '{{ ansible_env.HOME }}/.vim_runtime'
      depth: 1
    register: vimrc_sample_output

  - name: Install sample vimrc
    shell: 'sh ~/.vim_runtime/install_awesome_vimrc.sh'
    become_user: '{{ ansible_user_id }}'

  - name: Copy .vimrc file to correct destination
    template:
      src: .vimrc
      dest: '{{ ansible_env.HOME }}/.vimrc'
      owner: '{{ ansible_user_id }}'

  - name: Install plugins using vim-plug
    shell: vim +PlugInstall +qall

  tags:
    - install
    - install-vim
