- name: Clone zsh-syntax-highlightning
  git:
    repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
    dest: "{{ zsh_custom }}/plugins/zsh-syntax-highlighting"

- name: Clone zsh-autosuggestions
  git:
    repo: https://github.com/zsh-users/zsh-autosuggestions.git
    dest: "{{ zsh_custom }}/plugins/zsh-autosuggestions"
