
- block:
  - block:
    - name: Create ~/.fonts directory
      file:
        path: '{{ ansible_env.HOME }}/.fonts'
        state: directory

    - name: Install fonts
      copy:
        src: '{{ item }}'
        dest: '{{ ansible_env.HOME }}/.fonts/{{ item }}'
      with_lines: 'find {{ ansible_env.HOME }}/.dotfiles/roles/fonts/files'

    tags:
      - files
      - files-fonts

  - name: Install Fira Code font
    apt:
      name: fonts-firacode
      state: latest

  tags:
    - install
    - install-fonts
